MONGO:
  URI:
    ENABLED: false
    URL: ""
  HOST: "127.0.0.1"
  PORT: 27017
  DATABASE: "corexd"
  AUTHENTICATION:
    ENABLED: false
    USERNAME: ""
    PASSWORD: ""
    AUTHENTICATION-DATABASE: "admin"